# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec0c9de641379c8dfd2327daea1593806cc83119c1f911a0c43cbbcf73c4491bfea4b1c2847bf7cca3c01e1ee7753cfd3e7e2227e7dc635f1cc12214b0398102

test:
  secret_key_base: d9154da6090af5c7994f5c1c584151926a771603c901047c0fee7ff09419630958352bef302acf8b924dbeded00392025183ad4bc6440b860f885d4bf0034ec1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
